//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalNoticias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public long IdArchivo { get; set; }
        public long IdNoticia { get; set; }
        public string Ruta { get; set; }
        public bool Tipo { get; set; }
    
        public virtual Noticia Noticia { get; set; }
    }
}
