//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalNoticias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public long IdComentario { get; set; }
        public long IdUsuario { get; set; }
        public long IdNoticia { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Texto { get; set; }
    
        public virtual Noticia Noticia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
