//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalNoticias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Noticia()
        {
            this.Archivo = new HashSet<Archivo>();
            this.Comentario = new HashSet<Comentario>();
        }
    
        public long IdNoticia { get; set; }
        public long IdUsuario { get; set; }
        public string Titulo { get; set; }
        public string Texto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string TipoNoticia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archivo> Archivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
